name: ReleaseCI
on:
  push:
    branches:
      - master

jobs:

  # Build ./lambda/** code and update function.zip
  deploy_dataproc:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    
    - name: Clone 
      uses: actions/checkout@v2

    # Setup Go...
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.12.6' # The Go version to download (if necessary) and use.
    
    - name: Install dependencies
      run: |
        go get -u github.com/aws/aws-lambda-go/events github.com/aws/aws-lambda-go/lambda "github.com/sirupsen/logrus" golang.org/x/lint/golint

    - name: Run vet & lint
      run: |
        go vet ./lambda
        golint ./lambda
    
    - name: Build
      run: GOOS=linux go build -o ./lambda/deploy/main ./lambda/main.go ./lambda/token.go

    - name: Zip Function
      run: cd ./lambda/deploy && zip ./function.zip main

    - name: Deploy Function
      run: |
        export AWS_DEFAULT_REGION=us-east-1 &&\
        cd ./lambda/deploy &&\
          aws lambda update-function-code \
            --function-name DataProcess \
            --zip-file fileb://function.zip